BTC_HOLD_MINUTES = 15
BTC_CONTEXT_MINUTES = 30
BTC_LEVEL_BUFFER = 0.0005

XRP_BREAK_LOW = 1.600
XRP_BREAK_HIGH = 1.602
XRP_PULLBACK_FLOOR = 1.595
XRP_HOLD_CANDLES = 3

STRONG_GREEN_BODY_PCT = 0.45
CLOSE_NEAR_HIGH_PCT = 0.75
FOLLOW_THROUGH_MIN_PCT = 0.0005

POLL_SECONDS = 15
ALERT_COOLDOWN_SECONDS = 300

PREALERT_ON_SCORE_1 = True
PRINT_DETAILS_ON_FLIP = True

BTC_PRODUCT = "BTC-USD"
XRP_PRODUCT = "XRP-USD"

GRANULARITY = 60
LIMIT = 200

COINBASE_CANDLES = "https://api.exchange.coinbase.com/products/{product_id}/candles"